USE PIZZA;

SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;
SELECT * FROM PIZZA_TYPES;
SELECT * FROM PIZZAS;

# 1) TOTAL NO OF ORDERS 
SELECT COUNT(ORDER_ID) AS TOTAL_NO_OF_ORDERS FROM ORDERS;

# 2)TOTAL REVENUE
SELECT SUM(OD.QUANTITY * P.PRICE) AS TOTAL_REVENUE
FROM PIZZAS P
INNER JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID;

# 3) HIGHEST PRICE PIZZA
SELECT PIZZA_ID,PRICE  FROM PIZZAS
WHERE PRICE = (SELECT MAX(PRICE) FROM PIZZAS);

# 4) TOP MOST 5 ORDERED PIZZA
SELECT PT.PIZZA_TYPE_ID, PT.NAME, P.PIZZA_ID, COUNT(OD.QUANTITY) AS QTY
FROM ORDER_DETAILS OD
INNER JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID
INNER JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID 
GROUP BY PT.PIZZA_TYPE_ID, PT.NAME, P.PIZZA_ID
ORDER BY QTY DESC
LIMIT 5;
#######SELECT SUM(QUANTITY) FROM ORDER_DETAILS WHERE PIZZA_ID='big_meat_s';

# 5) ORDERS BY HOURS OF THE DAY
SELECT HOUR(TIME) AS HOURS_OF_DAY, COUNT(ORDER_ID) AS ORDER_S
FROM ORDERS
GROUP BY HOURS_OF_DAY
ORDER BY ORDER_S;

# 6) CATEGORY WISE DISTRIBUTION OF PIZZA
SELECT PT.CATEGORY, SUM(OD.QUANTITY) AS CATEGORY_COUNT
FROM ORDER_DETAILS OD
INNER JOIN PIZZAS P
ON OD.PIZZA_ID = P.PIZZA_ID 
INNER JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.CATEGORY ;

# 7) AVG NO OF PIZZAS ORDERED PER DAY
SELECT AVG(PER_DAY) AS AVG_PER_DAY FROM 
(SELECT O.DATE, SUM(OD.QUANTITY) AS PER_DAY
FROM ORDER_DETAILS OD
INNER JOIN ORDERS O
ON OD.ORDER_ID = O.ORDER_ID 
GROUP BY O.DATE)
PER_DAY;

# 8) TOP MOST 3 ORDERED PIZZA BASED ON REVENUE
SELECT PT.NAME,SUM(OD.QUANTITY * P.PRICE) AS REVENUE
FROM PIZZAS P
INNER JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
INNER JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.NAME
ORDER BY REVENUE DESC
LIMIT 3;

# 9) TOP MOST 3 REVENUE FOR CATEGORY
SELECT PT.NAME, PT.CATEGORY, SUM(OD.QUANTITY * P.PRICE) AS REVENUE
FROM PIZZAS P
INNER JOIN ORDER_DETAILS OD
ON P.PIZZA_ID = OD.PIZZA_ID
INNER JOIN PIZZA_TYPES PT
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.NAME, PT.CATEGORY
ORDER BY REVENUE DESC
LIMIT 3;


# 10) CALCULATE THE PERCENTAGE CONTRIBUTION
SELECT 
    PT.NAME AS PIZZA_NAME, 
    SUM(OD.QUANTITY * P.PRICE) AS REVENUE,
    (SUM(OD.QUANTITY * P.PRICE) / (SELECT SUM(OD.QUANTITY * P.PRICE) 
                                   FROM PIZZAS P
                                   INNER JOIN ORDER_DETAILS OD 
                                   ON P.PIZZA_ID = OD.PIZZA_ID) * 100) AS PERCENTAGE_CONTRIBUTION
FROM PIZZAS P
INNER JOIN ORDER_DETAILS OD 
ON P.PIZZA_ID = OD.PIZZA_ID
INNER JOIN PIZZA_TYPES PT 
ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY PT.NAME
ORDER BY PERCENTAGE_CONTRIBUTION DESC;

